### ISSUE TITLE
Figure out deployment

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-ideas#18]
We have everything working well locally with `create-react-app`, but need to figure out how to get the site to build after a push to dokku.  

A couple of options:  

- Add an nginx dokku buildpack, and an npm postinstall script to build the bundle/scss
- Add an express server, Procfile, etc to run a simple webserver

The buildpack option seems simpler at this point.

**Comment by allthesignals** [comment]
Out-of-the-box solutions through create-react-app, among others: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#static-server

**Comment by allthesignals** [comment]
This section is particularly important: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#serving-apps-with-client-side-routing. 

We want to avoid the hash token.

**Comment by chriswhong** [comment]
Closed by #22
