### ISSUE TITLE
Design and Layout

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ideas#2]
Let's make design consistent with planninglabs.nyc. 

@andycochran:

At standup, we talked about these views:
 - [x] Idea page view
     - [x] Includes Disqus comment box
 - [x] Idea list view
 - [x] Idea create view

**Comment by allthesignals** [comment]
Other design questions:
 - Table? Grid? List? 
 - Layout for card/list?
 - Glyphs for taxonomies?

**Comment by andycochran** [comment]
Ideas sketches: 
[Single](https://docs.google.com/drawings/d/1iVwrbL4yRIhh8VJndTr8y4iQn4usB9FGSN-d7bgaAK4/edit?usp=sharing)
[List](https://docs.google.com/drawings/d/1RzSPtZZ6a3xIhuFmLeeK5Ely_EXYTZEbjr5MByw87Mc/edit?usp=sharing)

**Comment by andycochran** [comment]
Closing this. All accounted for in other issues.
