### ISSUE TITLE
Add loading spinner

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-ideas#33]
The API call to Airtable takes a split second.  Let's add a spinner in place of the list while the data are loading.

**Comment by andycochran** [comment]
Maybe a [SCSS approach](http://tobiasahlin.com/spinkit/)? I like the 7th one.

**Comment by chriswhong** [comment]
Yes, I like spinkit!

**Comment by chriswhong** [comment]
Closed by #46
