### ISSUE TITLE
Set card min-height and truncate copy with multi-line ellipses 

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ideas#35]
Cards are different heights because of short description. @andycochran suggests making them equal height and handling overlong "short" descriptions in the cards.

![image](https://user-images.githubusercontent.com/5004319/28467854-3f634620-6dff-11e7-88fe-d3976a6bf2b1.png)

@ftlabs worked on this: https://github.com/ftlabs/ftellipsis

**Comment by andycochran** [comment]
I think we shouldn't truncate the short titles. Since the Labs team will write the short titles based on the information provided by the customer, we can control/predict their length. So, I've set a min height on the cards — which we can adjust this once we've worked out the proper max length.

**Comment by allthesignals** [comment]
Nice - is that true for the short description as well? I think I was referring to description in the title of this issue.

**Comment by chriswhong** [comment]
Closing, ideas have a min-height, we should control the length of descriptions manually
