### ISSUE TITLE
Add slugified version of division, objectives, and types fields for CSS

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ideas#36]
CSS will expect slugified version of fields of known types. If those types change or types are added, the SCSS will need to be updated appropriately.

**Comment by andycochran** [comment]
I've added `.label.[strategic_objectives]` classes, and stubbed them into the markup.

**Comment by andycochran** [comment]
Ack! Closed this because `strategic_objectives` are done. Reopening so we can finish the `project_types`.

**Comment by chriswhong** [comment]
Strategic objectives are complete, still want to integrate tags ("mapping", "data", "workflow"), still hard-coded.

**Comment by allthesignals** [comment]
Includes task of adding these tags into filter (the Ideas view)
