### ISSUE TITLE
Scroll to top on route transition

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ideas#44]
Possibly up for debate, should app scroll to top when route changes? Sometimes user can land mid-page and it's confusing

**Comment by chriswhong** [comment]
Just saw this, it's definitely awkward to not start at the top of the page after the route changes

**Comment by andycochran** [comment]
I don't think we're going to be linking to page anchors. I say +1 to scrollTop on route changes.

**Comment by chriswhong** [comment]
Pattern documented here: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md
