### ISSUE TITLE
Embed Airtable form into a route

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ideas#5]

**Comment by allthesignals** [comment]
Looks like Airtable just has an embed-able iFrame - not sure if there's anything more sophisticated than that. All I can think of is custom form that uses a proxied API endpoint. I don't know if it's worth it.

**Comment by chriswhong** [comment]
Iframe is the way to go on this for the time being, just need to make it not look too out of place with everything else.

**Comment by chriswhong** [comment]
Closed by #14
