### ISSUE TITLE
Disqus links in footer link to wrong path

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ideas#53]
![image](https://user-images.githubusercontent.com/5004319/28544616-d8bd14e2-7091-11e7-9e02-1a7ec16f0faa.png)
These "also on ideas.planninglabs.nyc" links link to '/ideas/project-name' instead of '/project-name'.

**Comment by chriswhong** [comment]
We were passing an old `path` prop to the Disqus component, fixed in 53415218aa8fdb7d98865dc250455e2e91d073ed

**Comment by allthesignals** [comment]
@chriswhong is the fix in 5341521 affected by #59?
